// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fklqvivyazegiskajuna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbHF2aXZ5YXplZ2lza2FqdW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjY2MDMsImV4cCI6MjA3MzgwMjYwM30.6OWcRHl7zY82Zyu1bW_f5RqrUr4KL4wQIiyQq6cKJQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});